# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facturador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('razon_social', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaElectronica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dte_version', models.CharField(max_length=4)),
                ('document_id', models.CharField(max_length=10)),
                ('folio', models.PositiveIntegerField()),
                ('fecha_emision', models.DateField()),
                ('tasa_iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_neto', models.IntegerField()),
                ('extra_data', models.CharField(max_length=50)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emitidas', to='einvoice.Facturador')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibidas', to='einvoice.Facturador')),
            ],
        ),
    ]
